### ISSUE TITLE
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

### ISSUE THREAD

**Issue by wilzamguerrero** [ddPn08/kohya-sd-scripts-webui#14]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
use 8-bit AdamW optimizer | {}
running training / 学習開始
num train images * repeats / 学習画像の数×繰り返し回数: 1575
num reg images / 正則化画像の数: 0
num batches per epoch / 1epochのバッチ数: 1575
num epochs / epoch数: 2
batch size per device / バッチサイズ: 1
gradient accumulation steps / 勾配を合計するステップ数 = 1
total optimization steps / 学習ステップ数: 1600
Traceback (most recent call last):
File "/content/stable-diffusion-webui/extensions/kohya-sd-scripts-webui/kohya_ss/train_network.py", line 642, in <module>
train(args)
File "/content/stable-diffusion-webui/extensions/kohya-sd-scripts-webui/kohya_ss/train_network.py", line 411, in train
metadata |= {
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

**Comment by ddPn08** [comment]
kohya-ss/sd-scripts recommends python3.10.
Using other versions may result in errors.
