### ISSUE TITLE
module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by SilverDash** [ddPn08/kohya-sd-scripts-webui#22]
```
`Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Installing requirements for kohya sd-scripts

Installing sd-dynamic-prompts requirements.txt

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed accelerate-0.18.0 bitsandbytes-0.35.4 diffusers-0.14.0 fastapi-0.94.1 gitpython-3.1.31 keras-2.12.0 protobuf-4.22.1 tensorboard-2.12.0 tensorboard-data-server-0.7.0 tensorflow-2.12.0 tensorflow-estimator-2.12.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers NOT installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero

Launching Web UI with arguments: --opt-sdp-attention
Traceback (most recent call last):
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\transformers\utils\import_utils.py", line 1110, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "I:\Users\Silver\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\transformers\modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\accelerate\accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:\Projects\stable-diffusion-webui-master\launch.py", line 356, in <module>
    start()
  File "I:\Projects\stable-diffusion-webui-master\launch.py", line 347, in start
    import webui
  File "I:\Projects\stable-diffusion-webui-master\webui.py", line 21, in <module>
    import pytorch_lightning # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torchmetrics\functional\text\bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\transformers\utils\import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "I:\Projects\stable-diffusion-webui-master\venv\lib\site-packages\transformers\utils\import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
module 'tensorflow' has no attribute 'io'`
```

web-ui version didn't matter. Spent the day trying to figure out the issue. I tried to manually install Tensorflow but I think the script uninstalls and installs it again automatically anyway.

**Comment by SilverDash** [comment]
Solution is to update tensor-board. this extension decides to enforce a bad version.

**Comment by SilverDash** [comment]
The issue is tensorboard. You need to use latest version. Also don't' enforce old gradio version
